spring.application.name=Source-Safe
spring.datasource.url=jdbc:postgresql://localhost:5432/sourcesafedatabase
spring.datasource.username=postgres
spring.datasource.password=postgres_pass_1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true